<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NoWarn>CS0436</NoWarn>
	</PropertyGroup>
	
	<PropertyGroup>
		<TargetFrameworks>net10.0;net9.0;net8.0</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FakeItEasy" Version="9.0.1" />
		<PackageReference Include="xunit.v3.extensibility.core" Version="4.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\LyricsScraperNET\LyricsScraperNET.csproj" />
	</ItemGroup>

</Project>
