<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<NoWarn>CS0436</NoWarn>
	</PropertyGroup>
	
	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FakeItEasy" Version="9.0.1" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
		<PackageReference Include="coverlet.collector" Version="3.1.2">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="xunit.v3" Version="4.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\LyricsScraperNET.TestShared\LyricsScraperNET.TestShared.csproj" />
		<ProjectReference Include="..\..\LyricsScraperNET\LyricsScraperNET.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="Providers\AZLyrics\Resources\Lyrics_Result_02.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\AZLyrics\Resources\Lyrics_Result_01.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Genius\instrumental_test_data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Genius\Resources\Lyrics_Result_02.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\LyricFind\Resources\Lyrics_Result_01.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\LyricFind\lyric_test_data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\LyricsFreak\lyric_test_data.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\LyricsFreak\Resources\Lyrics_Result_01.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\LyricsFreak\Resources\Lyrics_Result_03.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\LyricsFreak\Resources\Lyrics_Result_02.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Musixmatch\instrumental_test_data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Musixmatch\Resources\Lyrics_Result_01.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Musixmatch\lyric_test_data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Genius\Resources\Lyrics_Result_01.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Genius\lyric_test_data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\AZLyrics\lyric_test_data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\SongLyrics\Resources\Lyrics_Result_02.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\SongLyrics\Resources\Lyrics_Result_01.txt">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\SongLyrics\lyric_test_data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\KPopLyrics\lyric_test_data.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\KPopLyrics\Resources\Lyrics_Result_01.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\KPopLyrics\Resources\Lyrics_Result_02.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\KPopLyrics\Resources\Lyrics_Result_03.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\KPopLyrics\Resources\Lyrics_Result_04.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\KPopLyrics\Resources\Lyrics_Result_05.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Lrclib\lyric_test_data.json">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Providers\Lrclib\Resources\Lyrics_Result_01.txt">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
